// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv2Qeq210jf4P2nljdwZhqwr0vwdRH8bo',
    appId: '1:796521627908:web:3a071382c5f4720fbb9051',
    messagingSenderId: '796521627908',
    projectId: 'diet-tracking-f365a',
    authDomain: 'diet-tracking-f365a.firebaseapp.com',
    storageBucket: 'diet-tracking-f365a.firebasestorage.app',
    measurementId: 'G-QFFGN0KLVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEbzq-F_OAMxn7I2mxrbaXOkmrXpOzgg',
    appId: '1:796521627908:android:c25d5dd220421a5dbb9051',
    messagingSenderId: '796521627908',
    projectId: 'diet-tracking-f365a',
    storageBucket: 'diet-tracking-f365a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZD_r-J2mTT1rmYXb2Gz8zun_OdEaczSU',
    appId: '1:796521627908:ios:9fb3b78a02f8f805bb9051',
    messagingSenderId: '796521627908',
    projectId: 'diet-tracking-f365a',
    storageBucket: 'diet-tracking-f365a.firebasestorage.app',
    iosBundleId: 'com.example.dietTrackingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZD_r-J2mTT1rmYXb2Gz8zun_OdEaczSU',
    appId: '1:796521627908:ios:9fb3b78a02f8f805bb9051',
    messagingSenderId: '796521627908',
    projectId: 'diet-tracking-f365a',
    storageBucket: 'diet-tracking-f365a.firebasestorage.app',
    iosBundleId: 'com.example.dietTrackingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv2Qeq210jf4P2nljdwZhqwr0vwdRH8bo',
    appId: '1:796521627908:web:f185eeebf4cf4721bb9051',
    messagingSenderId: '796521627908',
    projectId: 'diet-tracking-f365a',
    authDomain: 'diet-tracking-f365a.firebaseapp.com',
    storageBucket: 'diet-tracking-f365a.firebasestorage.app',
    measurementId: 'G-43SM4PQCCW',
  );
}
