// Mocks generated by Mockito 5.4.6 from annotations
// in diet_tracking_project/test/database/data_migration_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:diet_tracking_project/database/auth_service.dart' as _i4;
import 'package:diet_tracking_project/database/local_storage_service.dart'
    as _i2;
import 'package:diet_tracking_project/model/nutrition_calculation_model.dart'
    as _i7;
import 'package:diet_tracking_project/model/user.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageService extends _i1.Mock
    implements _i2.LocalStorageService {
  MockLocalStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveGuestData({
    String? goal,
    double? heightCm,
    double? weightKg,
    double? goalWeightKg,
    double? goalHeightCm,
    String? health,
    List<String>? allergies,
    List<String>? weightReasons,
    String? dietPreference,
    int? age,
    String? gender,
    String? language,
    String? activityLevel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveGuestData, [], {
              #goal: goal,
              #heightCm: heightCm,
              #weightKg: weightKg,
              #goalWeightKg: goalWeightKg,
              #goalHeightCm: goalHeightCm,
              #health: health,
              #allergies: allergies,
              #weightReasons: weightReasons,
              #dietPreference: dietPreference,
              #age: age,
              #gender: gender,
              #language: language,
              #activityLevel: activityLevel,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> readGuestData() =>
      (super.noSuchMethod(
            Invocation.method(#readGuestData, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> hasGuestData() =>
      (super.noSuchMethod(
            Invocation.method(#hasGuestData, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasCompleteGuestOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#hasCompleteGuestOnboarding, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearGuestData() =>
      (super.noSuchMethod(
            Invocation.method(#clearGuestData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveData(String? key, dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#saveData, [key, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<dynamic> getData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [key]),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> removeData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeData, [key]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllFoodRecords() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllFoodRecords, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i5.User?>.empty(),
          )
          as _i3.Stream<_i5.User?>);

  @override
  _i3.Future<_i5.User?> signUpWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
            }),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<_i5.User?> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.User?> getUserData(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [uid]),
            returnValue: _i3.Future<_i6.User?>.value(),
          )
          as _i3.Future<_i6.User?>);

  @override
  _i3.Future<void> updateUserData(String? uid, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [uid, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveNutritionPlan(
    String? uid,
    Map<String, dynamic>? planData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveNutritionPlan, [uid, planData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getActiveNutritionPlan(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveNutritionPlan, [uid]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<_i7.NutritionCalculation?> getNutritionPlanForCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionPlanForCurrentUser, []),
            returnValue: _i3.Future<_i7.NutritionCalculation?>.value(),
          )
          as _i3.Future<_i7.NutritionCalculation?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getRecentFoodRecords(
    String? uid, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFoodRecords, [uid], {#limit: limit}),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<_i5.User?> signUpWithOnboardingData({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phone,
    String? gender,
    double? heightCm,
    double? weightKg,
    double? goalWeightKg,
    List<String>? allergies,
    int? age,
    String? goal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithOnboardingData, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
              #gender: gender,
              #heightCm: heightCm,
              #weightKg: weightKg,
              #goalWeightKg: goalWeightKg,
              #allergies: allergies,
              #age: age,
              #goal: goal,
            }),
            returnValue: _i3.Future<_i5.User?>.value(),
          )
          as _i3.Future<_i5.User?>);

  @override
  _i3.Future<bool> isEmailAlreadyInUse(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#isEmailAlreadyInUse, [email]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> testFirebaseConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testFirebaseConnection, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
