import 'dart:io';

import 'package:flutter/foundation.dart';

import '../../../record_view_home/data/repositories/food_record_repository_impl.dart';
import '../../../record_view_home/domain/entities/food_record_entity.dart';
import '../../../record_view_home/domain/repositories/food_record_repository.dart';
import '../../domain/entities/scanned_food_entity.dart';
import '../../domain/repositories/scanned_food_repository.dart';
import '../../../../services/cloudinary_service.dart';

/// Implementation of ScannedFoodRepository
class ScannedFoodRepositoryImpl implements ScannedFoodRepository {
  final CloudinaryService cloudinaryService;
  final FoodRecordRepository foodRecordRepository;

  ScannedFoodRepositoryImpl({
    CloudinaryService? cloudinaryService,
    FoodRecordRepository? foodRecordRepository,
  }) : cloudinaryService = cloudinaryService ?? CloudinaryService.fromConfig(),
       foodRecordRepository =
           foodRecordRepository ?? FoodRecordRepositoryImpl();

  @override
  Future<void> saveScannedFood(ScannedFoodEntity food) async {
    String uploadedUrl = food.imagePath;

    // 1. Upload image to Cloudinary if it's a local file path
    if (food.imagePath.isNotEmpty && !food.imagePath.startsWith('http')) {
      final file = File(food.imagePath);
      if (file.existsSync()) {
        uploadedUrl = await cloudinaryService.uploadImage(file);
      } else {
        debugPrint('File does not exist at: ${food.imagePath}');
        uploadedUrl = ''; // Reset path if file not found
      }
    }

    // 2. Create a unified FoodRecordEntity (ID will be generated by the repo)
    final foodRecord = FoodRecordEntity(
      foodName: food.foodName ?? 'Scanned Item',
      calories: food.calories ?? 0,
      date: food.scanDate,
      imagePath: uploadedUrl, // Use the potentially updated URL
      recordType: food.scanType == ScanType.barcode
          ? RecordType.barcode
          : RecordType.food,
      nutritionDetails: food.description,
      // Pass the new nutrition fields
      protein: food.protein,
      carbs: food.carbs,
      fat: food.fat,
      barcode: food.barcode,
    );

    // 3. Use the injected repository to save the record, centralizing logic
    await foodRecordRepository.saveFoodRecord(foodRecord);
  }
}
