// Mocks generated by Mockito 5.4.6 from annotations
// in diet_tracking_project/test/features/home_page/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:diet_tracking_project/features/home_page/domain/entities/home_info.dart'
    as _i2;
import 'package:diet_tracking_project/features/home_page/domain/repositories/home_repository.dart'
    as _i3;
import 'package:diet_tracking_project/features/home_page/domain/usecases/get_home_info_usecase.dart'
    as _i5;
import 'package:diet_tracking_project/services/notification_service.dart'
    as _i7;
import 'package:diet_tracking_project/services/permission_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeInfo_0 extends _i1.SmartFake implements _i2.HomeInfo {
  _FakeHomeInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeRepository_1 extends _i1.SmartFake
    implements _i3.HomeRepository {
  _FakeHomeRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeInfo> getHomeInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getHomeInfo, []),
            returnValue: _i4.Future<_i2.HomeInfo>.value(
              _FakeHomeInfo_0(this, Invocation.method(#getHomeInfo, [])),
            ),
          )
          as _i4.Future<_i2.HomeInfo>);

  @override
  _i4.Future<void> updateCurrentIndex(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#updateCurrentIndex, [index]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetHomeInfoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHomeInfoUseCase extends _i1.Mock
    implements _i5.GetHomeInfoUseCase {
  MockGetHomeInfoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_1(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i3.HomeRepository);

  @override
  _i4.Future<_i2.HomeInfo> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.HomeInfo>.value(
              _FakeHomeInfo_0(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.HomeInfo>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i6.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isCameraPermissionGranted() =>
      (super.noSuchMethod(
            Invocation.method(#isCameraPermissionGranted, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> requestNotificationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isNotificationPermissionGranted() =>
      (super.noSuchMethod(
            Invocation.method(#isNotificationPermissionGranted, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [LocalNotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationService extends _i1.Mock
    implements _i7.LocalNotificationService {
  MockLocalNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void resetWaterReminderSessionFlag() => super.noSuchMethod(
    Invocation.method(#resetWaterReminderSessionFlag, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showSimpleNotification({
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showSimpleNotification, [], {
              #title: title,
              #body: body,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleWaterReminderOncePerSession({
    Duration? delay = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleWaterReminderOncePerSession, [], {
              #delay: delay,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
