// Mocks generated by Mockito 5.4.6 from annotations
// in diet_tracking_project/test/features/profile_view_home/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:diet_tracking_project/features/profile_view_home/domain/entities/profile_entity.dart'
    as _i4;
import 'package:diet_tracking_project/features/profile_view_home/domain/repositories/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ProfileEntity?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i3.Future<_i4.ProfileEntity?>.value(),
          )
          as _i3.Future<_i4.ProfileEntity?>);

  @override
  bool isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<String> uploadAvatar(_i5.File? imageFile, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAvatar, [imageFile, userId]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#uploadAvatar, [imageFile, userId]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateUserProfile(_i4.ProfileEntity? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearLocalData() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
