// Mocks generated by Mockito 5.4.6 from annotations
// in diet_tracking_project/test/features/record_view_home/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:diet_tracking_project/features/record_view_home/domain/entities/food_record_entity.dart'
    as _i4;
import 'package:diet_tracking_project/features/record_view_home/domain/repositories/food_record_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FoodRecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodRecordRepository extends _i1.Mock
    implements _i2.FoodRecordRepository {
  MockFoodRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveFoodRecord(_i4.FoodRecordEntity? foodRecord) =>
      (super.noSuchMethod(
            Invocation.method(#saveFoodRecord, [foodRecord]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.FoodRecordEntity>> getFoodRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getFoodRecords, []),
            returnValue: _i3.Future<List<_i4.FoodRecordEntity>>.value(
              <_i4.FoodRecordEntity>[],
            ),
          )
          as _i3.Future<List<_i4.FoodRecordEntity>>);

  @override
  _i3.Future<void> deleteFoodRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFoodRecord, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
