// Mocks generated by Mockito 5.4.6 from annotations
// in diet_tracking_project/test/features/chat_bot_view_home/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:diet_tracking_project/features/chat_bot_view_home/domain/entities/chat_message_entity.dart'
    as _i8;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/entities/chat_session_entity.dart'
    as _i4;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/entities/user_data_entity.dart'
    as _i10;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/repositories/chat_repository.dart'
    as _i5;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/repositories/chat_session_repository.dart'
    as _i12;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/repositories/user_repository.dart'
    as _i9;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/usecases/create_new_chat_session_usecase.dart'
    as _i16;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/usecases/food_scan_analysis_usecase.dart'
    as _i14;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/usecases/generate_food_suggestion_usecase.dart'
    as _i13;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/usecases/send_message_usecase.dart'
    as _i2;
import 'package:diet_tracking_project/features/chat_bot_view_home/domain/usecases/validate_message_usecase.dart'
    as _i3;
import 'package:diet_tracking_project/features/record_view_home/domain/entities/food_record_entity.dart'
    as _i15;
import 'package:diet_tracking_project/model/nutrition_calculation_model.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSendMessageResult_0 extends _i1.SmartFake
    implements _i2.SendMessageResult {
  _FakeSendMessageResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidationResult_1 extends _i1.SmartFake
    implements _i3.ValidationResult {
  _FakeValidationResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatSessionEntity_2 extends _i1.SmartFake
    implements _i4.ChatSessionEntity {
  _FakeChatSessionEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i5.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> sendMessage(
    String? message,
    Map<String, dynamic>? contextData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message, contextData]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#sendMessage, [message, contextData]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i8.ChatMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i6.Future<List<_i8.ChatMessageEntity>>.value(
              <_i8.ChatMessageEntity>[],
            ),
          )
          as _i6.Future<List<_i8.ChatMessageEntity>>);

  @override
  _i6.Future<void> saveChatMessage(_i8.ChatMessageEntity? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatMessage, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i10.UserDataEntity?> getCurrentUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserData, []),
            returnValue: _i6.Future<_i10.UserDataEntity?>.value(),
          )
          as _i6.Future<_i10.UserDataEntity?>);

  @override
  _i6.Future<bool> isUserAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isUserAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getCurrentUserId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserId, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i11.NutritionCalculation?> getNutritionPlan() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionPlan, []),
            returnValue: _i6.Future<_i11.NutritionCalculation?>.value(),
          )
          as _i6.Future<_i11.NutritionCalculation?>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getRecentFoodRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFoodRecords, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [ChatSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSessionRepository extends _i1.Mock
    implements _i12.ChatSessionRepository {
  MockChatSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i4.ChatSessionEntity>> getAllSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSessions, []),
            returnValue: _i6.Future<List<_i4.ChatSessionEntity>>.value(
              <_i4.ChatSessionEntity>[],
            ),
          )
          as _i6.Future<List<_i4.ChatSessionEntity>>);

  @override
  _i6.Future<_i4.ChatSessionEntity?> getSessionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionById, [id]),
            returnValue: _i6.Future<_i4.ChatSessionEntity?>.value(),
          )
          as _i6.Future<_i4.ChatSessionEntity?>);

  @override
  _i6.Future<void> saveSession(_i4.ChatSessionEntity? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSession(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getCurrentSessionId() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSessionId, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> setCurrentSessionId(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentSessionId, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> createNewSession({String? title}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewSession, [], {#title: title}),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createNewSession, [], {#title: title}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String?> getMostRecentSessionIdFromCloud() =>
      (super.noSuchMethod(
            Invocation.method(#getMostRecentSessionIdFromCloud, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);
}

/// A class which mocks [SendMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendMessageUseCase extends _i1.Mock
    implements _i2.SendMessageUseCase {
  MockSendMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.SendMessageResult> execute(
    String? message, {
    Map<String, dynamic>? extraContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #execute,
              [message],
              {#extraContext: extraContext},
            ),
            returnValue: _i6.Future<_i2.SendMessageResult>.value(
              _FakeSendMessageResult_0(
                this,
                Invocation.method(
                  #execute,
                  [message],
                  {#extraContext: extraContext},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.SendMessageResult>);
}

/// A class which mocks [ValidateMessageUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateMessageUseCase extends _i1.Mock
    implements _i3.ValidateMessageUseCase {
  MockValidateMessageUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ValidationResult execute(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [message]),
            returnValue: _FakeValidationResult_1(
              this,
              Invocation.method(#execute, [message]),
            ),
          )
          as _i3.ValidationResult);
}

/// A class which mocks [GenerateFoodSuggestionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateFoodSuggestionUseCase extends _i1.Mock
    implements _i13.GenerateFoodSuggestionUseCase {
  MockGenerateFoodSuggestionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String execute({
    required String? ingredients,
    required String? budget,
    required String? mealType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #ingredients: ingredients,
              #budget: budget,
              #mealType: mealType,
            }),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#execute, [], {
                #ingredients: ingredients,
                #budget: budget,
                #mealType: mealType,
              }),
            ),
          )
          as String);
}

/// A class which mocks [BuildFoodScanAnalysisPromptUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildFoodScanAnalysisPromptUseCase extends _i1.Mock
    implements _i14.BuildFoodScanAnalysisPromptUseCase {
  MockBuildFoodScanAnalysisPromptUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String execute(_i15.FoodRecordEntity? r) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [r]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#execute, [r]),
            ),
          )
          as String);
}

/// A class which mocks [CreateNewChatSessionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNewChatSessionUseCase extends _i1.Mock
    implements _i16.CreateNewChatSessionUseCase {
  MockCreateNewChatSessionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ChatSessionEntity> execute({String? title}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#title: title}),
            returnValue: _i6.Future<_i4.ChatSessionEntity>.value(
              _FakeChatSessionEntity_2(
                this,
                Invocation.method(#execute, [], {#title: title}),
              ),
            ),
          )
          as _i6.Future<_i4.ChatSessionEntity>);
}
